package cookbook.models;
// Generated 2018-12-07 22:21:43 by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Amountingredients generated by hbm2java
 */
@Entity
@Table(name = "amountingredients")
public class Amountingredients implements java.io.Serializable {

	private AmountingredientsId id;
	private Ingredients ingredients;
	private Recipes recipes;

	public Amountingredients() {
	}

	public Amountingredients(AmountingredientsId id, Ingredients ingredients, Recipes recipes) {
		this.id = id;
		this.ingredients = ingredients;
		this.recipes = recipes;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "amount", column = @Column(name = "amount", nullable = false, precision = 10)),
			@AttributeOverride(name = "ingredientsName", column = @Column(name = "ingredients_name", nullable = false, length = 30)),
			@AttributeOverride(name = "recipesId", column = @Column(name = "recipes_id", nullable = false)) })
	public AmountingredientsId getId() {
		return this.id;
	}

	public void setId(AmountingredientsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ingredients_name", nullable = false, insertable = false, updatable = false)
	public Ingredients getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Ingredients ingredients) {
		this.ingredients = ingredients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "recipes_id", nullable = false, insertable = false, updatable = false)
	public Recipes getRecipes() {
		return this.recipes;
	}

	public void setRecipes(Recipes recipes) {
		this.recipes = recipes;
	}

}
