package cookbook.models;
// Generated 2018-12-07 22:21:43 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name = "ingredients")

public class Ingredients implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String name;
	private String unit;
	private Set<Amountingredients> amountingredientses = new HashSet<Amountingredients>(0);

	public Ingredients() {
	}

	public Ingredients(String name, String unit) {
		this.name = name;
		this.unit = unit;
	}
	

	public Ingredients(String name, String unit, Set<Amountingredients> amountingredientses) {
		this.name = name;
		this.unit = unit;
		this.amountingredientses = amountingredientses;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "unit", length = 15)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingredients")
	public Set<Amountingredients> getAmountingredientses() {
		return this.amountingredientses;
	}

	public void setAmountingredientses(Set<Amountingredients> amountingredientses) {
		this.amountingredientses = amountingredientses;
	}

}
