package cookbook.models;
// Generated 2018-12-07 22:21:43 by Hibernate Tools 5.2.11.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Photos generated by hbm2java
 */
@Entity
@Table(name = "photos")
public class Photos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String path;
	private Recipes recipes;

	public Photos() {
	}

	public Photos(String path) {
		super();
		this.path = path;
	}

	public Photos(String path, Recipes recipes) {
		this.path = path;
		this.recipes = recipes;
	}

	@Id

	@Column(name = "path", unique = true, nullable = false, length = 50)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade =CascadeType.REMOVE)
	@JoinColumn(name = "recipes_id", nullable = false)
	public Recipes getRecipes() {
		return this.recipes;
	}

	public void setRecipes(Recipes recipes) {
		this.recipes = recipes;
	}

}
